sudo: false
language: c
os:
  - linux
  - osx
dist: trusty
addons:
  apt:
    packages:
    - python-pygments
    - libssh2-1-dev
before_script:
  - export RELEASE=`curl --silent https://api.github.com/repos/nim-lang/nightlies/releases/latest | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'`
  - export TXZ=`curl --silent https://api.github.com/repos/nim-lang/nightlies/releases/latest | grep '"name":' | sed -E 's/.*"([^"]+)".*/\1/' | grep linux`
  - export VERSION=`echo $TXZ | cut -d"-" -f 2,2`
  - echo "RELEASE = $RELEASE, TXZ = $TXZ, VERSION = $VERSION"
  - curl -L --silent -o $TXZ "https://github.com/nim-lang/nightlies/releases/download/$RELEASE/$TXZ"
  - tar xf $TXZ
  - cd nim-$VERSION
  - sh build.sh
  - bin/nim c koch
  - ./koch boot -d:release
  - ./koch nimble
  - export PATH=$(pwd)/bin:~/.nimble/bin:$PATH
  - cd ..
script:
  - nimble install -y
  - nimble test
